invoicer/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.startinvoice, name="new-invoice"),
    path('priceband/<int:bandid>/', views.priceband, name="priceband"),
    path('invoice/', views.startinvoice),
    path('invoice/<contactid>/', views.invoice, name="invoice"),
    path('bill/<contactid>/', views.invoice, {'bill': True},
         name="bill"),
    path('product/', views.product, name="add-product"),
    path('product/<int:productid>/', views.product, name="edit-product"),
    path('ajax/contact-completions.json', views.contact_completions,
         name="contact-completions"),
    path('ajax/item-completions.json', views.item_completions,
         name="item-completions"),
    path('ajax/item-details.json', views.item_details,
         name="item-details"),
    path('ajax/productcode-check.json', views.productcode_check),
    path('xero/callback/', views.xero_callback),
]

miltonxero/urls.py
from django.urls import include, path
from django.contrib import admin

admin.autodiscover()

admin.site.site_header = 'Milton Invoice Tool'

import invoicer.urls

urlpatterns = [
    path('admin/', admin.site.urls),
] + invoicer.urls.urlpatterns

invoicer/models.py
from django.db import models
from django.db.models import Q
from decimal import Decimal, ROUND_UP
from django.conf import settings
from django.urls import reverse
import decimal

zero = Decimal("0.00")
penny = Decimal("0.01")
fifty_pence = Decimal("0.50")
pound = Decimal("1.00")


class CaseInsensitiveFieldMixin:
    """
    Field mixin that uses case-insensitive lookup alternatives if they exist.
    """
    LOOKUP_CONVERSIONS = {
        'exact': 'iexact',
        'contains': 'icontains',
        'startswith': 'istartswith',
        'endswith': 'iendswith',
        'regex': 'iregex',
    }
    def get_lookup(self, lookup_name):
        converted = self.LOOKUP_CONVERSIONS.get(lookup_name, lookup_name)
        return super().get_lookup(converted)


class CICharField(CaseInsensitiveFieldMixin, models.CharField):
    pass


class PriceBand(models.Model):
    """A named group of pricing details."""
    name = models.CharField(max_length=40, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('priceband', args=[self.pk])

    def apply_rules_for(self, item):
        """Price per barrel, rules and account for an invoice item

        Work out the price per barrel; also record all the rules that were
        applied and the intermediate results.

        Return (price, account, list of rules)
        """
        rules = Price.objects.\
                filter(Q(band=self) | Q(band__isnull=True)).\
                filter(Q(type=item.product.type) | Q(type__isnull=True)).\
                filter(Q(abv=item.product.abv) | Q(abv__isnull=True)).\
                filter(Q(isSwap=item.product.swap) | Q(isSwap__isnull=True)).\
                filter(Q(isBill=item.isBill) | Q(isBill__isnull=True)).\
                filter(Q(product=item.product) | Q(product__isnull=True)).\
                filter(Q(unit=item.unit) | Q(unit__isnull=True)).\
                filter(Q(contact=item.contact) | Q(contact__isnull=True)).\
                order_by('priority').\
                all()
        price = zero
        account = "undefined"
        applied = []
        for r in rules:
            price, account = r.apply(item, price, account)
            applied.append((r, f"{price} / {account}"))
        return price, account, applied


class Contact(models.Model):
    """Extra details for Xero contacts.

    name is just a cache; it isn't used for auto-complete.  updated is
    the time the cache was last updated.  Additional cached fields:
    bill_{days,terms} and invoice_{days,terms}.
    """
    xero_id = models.CharField(max_length=36, unique=True) # uuid
    priceband = models.ForeignKey(PriceBand, on_delete=models.CASCADE)
    notes = models.CharField(max_length=500, blank=True, default='')
    name = models.CharField(max_length=500) # xero max is 500
    updated = models.DateTimeField()
    TERMS_CHOICES = (
        ("DAYSAFTERBILLDATE", "day(s) after bill date"),
        ("DAYSAFTERBILLMONTH", "day(s) after bill month"),
        ("OFCURRENTMONTH", "of the current month"),
        ("OFFOLLOWINGMONTH", "of the following month"),
    )
    bill_days = models.IntegerField(null=True, blank=True)
    bill_terms = models.CharField(max_length=20, choices=TERMS_CHOICES,
                                  blank=True)
    invoice_days = models.IntegerField(null=True, blank=True)
    invoice_terms = models.CharField(max_length=20, choices=TERMS_CHOICES,
                                     blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('invoice', args=[self.xero_id])


class ProductType(models.Model):
    """Type of product, eg. real ale or craft keg
    """
    name = models.CharField(max_length=80)

    def __str__(self):
        return self.name


class Unit(models.Model):
    """A unit in which products are sold"""
    name = models.CharField(max_length=10, help_text="Unit names with spaces "
                            "in may require code changes to work")
    size = models.DecimalField(max_digits=5, decimal_places=4,
                               help_text="Size in barrels")
    type = models.ForeignKey(ProductType, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Product(models.Model):
    code = CICharField(max_length=30, unique=True) # xero max is 30
    name = models.CharField(max_length=80, unique=True) # XXX xero max is 50, and we're adding the ABV too
    abv = models.DecimalField(max_digits=3, decimal_places=1)
    type = models.ForeignKey(ProductType, on_delete=models.CASCADE)
    swap = models.BooleanField(default=True)
    sent = models.BooleanField(default=False, help_text="Has this product code "
                               "been sent to Xero yet?")

    def __str__(self):
        # This is used as the Xero item description
        return "{} ({}% ABV)".format(self.name,self.abv)

    class Meta:
        ordering = ['name']

    def get_absolute_url(self):
        return reverse('edit-product', args=[self.pk])


def _round_up_to(amount, multiple):
    difference = amount % multiple
    if difference:
        amount = amount + multiple - difference
    return amount

def _vatinc_roundup_adjustment(item, current_price, multiple):
    vatinc_price = item.unit.size * current_price * settings.VAT_MULTIPLIER
    desired_price = _round_up_to(vatinc_price, multiple)
    difference_inc_vat = desired_price - vatinc_price
    difference_ex_vat = difference_inc_vat / settings.VAT_MULTIPLIER
    difference_per_barrel = difference_ex_vat / item.unit.size
    adjustment = difference_per_barrel.quantize(penny)
    return adjustment

def _round_item_up_to(item, current_price, multiple):
    item_price = item.unit.size * current_price
    rounded_item_price = _round_up_to(item_price, multiple)
    rounded_barrel_price = rounded_item_price / item.unit.size
    return rounded_barrel_price


class ProgramRule(models.Model):
    """A pricing rule implemented in code"""
    name = models.CharField(max_length=80, unique=True)
    code = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def apply(self, item, price, account):
        if self.code == "vat-roundup-pound":
            price = price + _vatinc_roundup_adjustment(
                item, price, pound)
        elif self.code == "vat-roundup-50p":
            price = price + _vatinc_roundup_adjustment(
                item, price, fifty_pence)
        elif self.code == "barrel-roundup-pound":
            price = _round_up_to(price, pound)
        elif self.code == "item-roundup-pound":
            price = _round_item_up_to(item, price, pound)
        elif self.code == "item-roundup-50p":
            price = _round_item_up_to(item, price, fifty_pence)
        elif self.code == "multiply-by-abv":
            price = (price * item.product.abv).quantize(penny)
        elif self.code.startswith("multiply-by-"):
            try:
                price = (price * Decimal(self.code[12:])).quantize(penny)
            except decimal.InvalidOperation:
                pass

        return price, account


class Price(models.Model):
    """A rule applied to price calculations that match the criteria"""
    # Criteria:
    band = models.ForeignKey(PriceBand, blank=True, null=True,
                             on_delete=models.CASCADE)
    type = models.ForeignKey(ProductType, blank=True, null=True,
                             on_delete=models.CASCADE)
    abv = models.DecimalField(max_digits=3, decimal_places=1,
                              blank=True, null=True)
    isSwap = models.BooleanField(
        null=True,
        help_text="Match on whether the product has the 'swap' tickbox "
        "set; 'Unknown' matches either way")
    isBill = models.BooleanField(
        null=True,
        help_text="Match on whether we are preparing an invoice or a "
        "bill; 'Unknown' matches either way")
    product = models.ForeignKey(Product, blank=True, null=True,
                                on_delete=models.CASCADE)
    unit = models.ForeignKey(Unit, blank=True, null=True,
                             on_delete=models.CASCADE)
    contact = models.ForeignKey(Contact, blank=True, null=True,
                                on_delete=models.CASCADE)
    # Rules to apply:
    priority = models.IntegerField(
        default=100,
        help_text="Rules are applied in order of priority, with higher values "
        "being applied later")
    price = models.DecimalField(
        max_digits=6, decimal_places=2, blank=True, null=True,
        help_text="The amount to increase the price per barrel when this rule "
        "is applied")
    absolute_price = models.DecimalField(
        max_digits=6, decimal_places=2, blank=True, null=True,
        help_text="The new price per barrel when this rule is applied, ignoring "
        "prices set by any previous rules")
    rule = models.ForeignKey(
        ProgramRule, blank=True, null=True, on_delete=models.CASCADE,
        help_text="A programmed rule to alter the price and/or account")
    account = models.CharField(
        max_length=10, blank=True,
        help_text="The value to use for the Xero account when this rule is "
        "applied")
    # Just a comment, not used anywhere
    comment = models.CharField(
        max_length=80, blank=True)

    class Meta:
        ordering = ['priority']

    def __str__(self):
        things = []
        if self.band:
            things.append(self.band.name)
        if self.type:
            things.append(self.type.name)
        if self.abv:
            things.append(str(self.abv))
        if self.isSwap != None:
            things.append("swap" if self.isSwap else "not-swap")
        if self.isBill != None:
            things.append("bill" if self.isBill else "invoice")
        if self.product:
            things.append(str(self.product))
        if self.unit:
            things.append(self.unit.name)

invoicer/templates/invoicer/invoice.html
{% extends "base.html" %}
{% load static %}
{% block scripts %}
<script type="text/javascript" src="{% static "auto-complete.js" %}"></script>
<link rel="STYLESHEET" type="text/css" href="{% static "auto-complete.css" %}">
<script type="text/javascript">
  var params = {
    priceband: {{priceband.pk}},
    bill: "{{bill}}",
    contact: {{contactnumber}},
    item_completions_url: "{% url "item-completions" %}",
    item_details_url: "{% url "item-details" %}",
  };
</script>
<script type="text/javascript" src="{% static "invoicer/invoice-updates.js" %}"></script>
{% endblock %}
{% block title %}{{contactname}} {% if bill %}bill{% else %}invoice{% endif %}{% endblock %}
{% block body %}
<h1>{% if bill %}Bill from{% else %}Invoice for{% endif %} {{contactname}}</h1>
<form method="POST" id="invoiceform">{% csrf_token %}
  {{cform.as_p}}
  {{iform.management_form}}
  <table class="invoiceitems">
    <thead>
      <tr>
	{% if iform.can_delete %}
	<th scope="col">Delete</th>
	{% endif %}
	<th scope="col">Item</th>
	<th scope="col">Gyle</th>
	<th scope="col">ABV</th>
	<th scope="col">Barrels</th>
	<th scope="col">Price/barrel</th>
	<th scope="col">Total ex&nbsp;VAT</th>
	<th scope="col">Total inc&nbsp;VAT</th>
	<th scope="col">Account</th>
	<th></th>
      </tr>
    </thead>
    <tbody>
      {% for form in iform %}
      <tr>
	{% if iform.can_delete %}
	<td class="deletebutton">{{form.DELETE}}</td>
	{% endif %}
	<td class="invoiceitem">
	  {{form.item.as_widget}}
	  {% if form.item.errors %}
	  <ul class="errorlist">
	    {% for err in form.item.errors %}
	    <li>{{err}}</li>
	    {% endfor %}
	  </ul>
	  {% endif %}
	</td>
	<td class="invoiceitemgyle">
	  {{form.gyle.as_widget}}
	  {% if form.gyle.errors %}
	  <ul class="errorlist">
	    {% for err in form.gyle.errors %}
	    <li>{{err}}</li>
	    {% endfor %}
	  </ul>
	  {% endif %}
	</td>
	<td id="{{form.item.html_name}}-abv">{{form.abv}}</td>
	<td id="{{form.item.html_name}}-barrels">{{form.barrels}}</td>
	<td id="{{form.item.html_name}}-barrelprice" class="price">
	  {% include "invoicer/pricedetail.html" with price=form.barrelprice reasons=form.barrelreasons product=form.product %}
	</td>
	<td id="{{form.item.html_name}}-total" class="price exvat">{{form.totalprice}}</td>
	<td id="{{form.item.html_name}}-incvat" class="price incvat">{{form.priceincvat}}</td>
	<td id="{{form.item.html_name}}-account">{{form.account}}</td>
	<td id="{{form.item.html_name}}-error" class="error">{% for e in form.non_field_errors %}{{e}}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
      </tr>
      <script type="text/javascript">
	addAutoComplete("{{form.item.html_name}}");
      </script>
      {% endfor %}
    </tbody>
    <tfoot>
      <tr><td colspan="6"></td>
	<td id="total-ex-vat" class="price"></td>
	<td id="total-inc-vat" class="price"></td>
	<td colspan="2"></td>
      </tr>
    </tfoot>
  </table>
  <p><a href="{% url 'add-product' %}" target="_blank">New product.</a> (Follow link from price/barrel to edit existing products.)</p>
  <input type="submit" name="save" value="Save / update">
  <input type="submit" name="send" value="Send to Xero and view in Xero">
  <input type="submit" name="send-background" value="Send to Xero and start another">
  <input type="submit" name="clear" value="Clear invoice without sending">
</form>
<script type="text/javascript">
  $('input[type=checkbox]').each(function () {
  this.tabIndex=-1;
  });
  updateTotals();

  $( function() {
  $("#id_date").datepicker({
    dateFormat: "dd/mm/yy"});
  });
</script>

{% if rules %}
<h3>Price rules that apply only to this contact</h3>
<ul>
  {% for r in rules %}
  <li><a href="{% url "admin:invoicer_price_change" r.pk %}">{{r}}</a></li>
  {% endfor %}
</ul>
{% endif %}

<p><a href="{% url "new-invoice" %}">Choose another contact</a></p>
<p><a href="https://go.xero.com/organisationlogin/default.aspx?shortcode={{shortcode}}&amp;redirecturl=/AccountsReceivable/Search.aspx?invoiceStatus=INVOICESTATUS/DRAFT">Go to draft invoices</a></p>
<p class="helptext">Hint: You can bookmark this page if you regularly
{% if bill %}receive bills from{% else %}send invoices to{% endif %}
this {% if bill %}supplier{% else %}customer{% endif %}.</p>

{% endblock %}

invoicer/templates/invoicer/invoicewarnings.html
{% extends "base.html" %}
{% load static %}
{% block title %}Warnings{% endblock %}
{% block body %}
<h1>Created with warnings</h1>

<p>The invoice or bill has successfully been sent to Xero.  However,
  Xero included some warnings in its response:</p>

<ul>
  {% for w in warnings %}
  <li>{{w}}</li>
  {% endfor %}
</ul>

<p><a href="{{iurl}}">Click here to continue to Xero</a></p>
{% endblock %}

invoicer/templates/invoicer/priceband.html
{% extends "base.html" %}
{% block title %}{{band.name}} price band{% endblock %}
{% block body %}
<h1>{{band.name}} price band</h1>

<p><a href="{% url "admin:invoicer_priceband_change" band.pk %}">Rename / delete</a> - <a href="/">Back</a></p>

<div id="tabs" style="clear: both;">
  <ul>
    {% if abvs %}<li><a href="#pricetable">Base prices</a></li>{% endif %}
    {% if others %}<li><a href="#others">Other rules</a></li>{% endif %}
    <li><a href="#upload">Upload new table</a></li>
  </ul>
{% if abvs %}
<div id="pricetable" name="pricetable">
  <p>Rules that match only on price band, product type and ABV:</p>
  <table>
    <thead>
      <tr>
	<th>ABV</th>
	{% for t in types %}
	<th>{{t.name}} price</th>
	{% endfor %}
      </tr>
    </thead>
    <tbody>
      {% for row in abvs %}
      <tr>
	{% for val in row %}
	<td>{{val}}</td>
	{% endfor %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endif %}

{% if others %}
<div name="others" id="others">
  <p>Other rules that can affect this price band:<p>
  <ul>
    {% for o in others %}
    <li><a href="{% url "admin:invoicer_price_change" o.pk %}">{{o}}</a></li>
    {% endfor %}
  </ul>
  <p><a href="{% url "admin:invoicer_price_changelist" %}">Edit price rules</a></p>
</div>
{% endif %}

<div id="upload">
  <form enctype="multipart/form-data" method="post">{% csrf_token %}
    {{form.as_p}}
    <input type="submit" name="update" value="Update price band">
  </form>

  <p>The CSV file must be in the following format:</p>
  <p>The first row contains headers, not data.  The header for the
  first column must be "ABV".  The headers for subsequent columns must
  be names of product types ("Cask ale", etc.).  Processing stops at
  the first blank header; subsequent headers are ignored.</p>
  <p>Subsequent rows are processed based on the contents of the first
    column:</p>
  <dl>
    <dd>Blank</dd><dt>The row is ignored</dt>
    <dd>Numeric</dd><dt>The number is treated as an ABV.  The second
    and subsequent columns are used as the base prices for this ABV,
    for the product types in the column header.</dt>
  </dl>
</div>
</div>
<script type="text/javascript">
  $(function() {
    $("#tabs").tabs({
      collapsible: true});
  });
</script>

{% endblock %}

invoicer/templates/invoicer/pricedetail.html
{% if price != "" %}
<a href="{% url 'edit-product' product.pk %}" class="help_link" tabindex="-1" target="_blank">{{price}}</a>
<div class="help">
  {% if reasons %}
  <table class="pricereason">
    {% for r, p in reasons %}
    <tr><td>{{r}}</td><td class="price">{{p}}</td></tr>
    {% endfor %}
  </table>
  {% endif %}
</div>
{% endif %}

invoicer/templates/invoicer/product.html
{% extends "base.html" %}
{% block title %}{% if product %}{{product.name}} details{% else %}New Product{% endif %}{% endblock %}
{% block body %}
{% if product %}
<h1>Update {{product.name}} ({{product.abv}}% ABV)</h1>
{% else %}
<h1>New Product</h1>
{% endif %}

<form method="post">{% csrf_token %}
  <table class="kvtable">
    {{form.as_table}}
  </table>
  <input type="submit" name="send" value="{% if product %}Update{% else %}Create{% endif %}">
</form>

{% if product %}
<table class="productprices">
  <colgroup>
    <col>
    {% for b in bands %}
    <col span="2" class="priceband">
    {% endfor %}
  </colgroup>
  <thead>
    <tr>
      <th></th>
      {% for b in bands %}
      <th colspan="2">{{b.name}}</th>
      {% endfor %}
    </tr>
    <tr>
      <th></th>
      {% for b in bands %}
      <th>ex VAT</th><th>inc VAT</th>
      {% endfor %}
    </tr>
  </thead>
  <tbody>
    {% for u in units %}
    <tr>
      <th>{{u.unit.name}}</th>
      {% for b in u.bandinfo %}
      <td><a href="#" class="help_link">{{b.price}}</a>
	<div class="help">
	  <table class="pricereason">
	    {% for r, p in b.reasons %}
	    <tr><td>{{r}}</td><td class="price">{{p}}</td></tr>
	    {% endfor %}
	  </table>
	</div>
      </td>
      <td>{{b.priceincvat}}</td>
      {% endfor %}
    </tr>
    {% endfor %}
  </tbody>
</table>
{% if rules %}
<h3>Price rules that apply only to this product</h3>
<ul>
  {% for r in rules %}
  <li><a href="{% url "admin:invoicer_price_change" r.pk %}">{{r}}</a></li>
  {% endfor %}
</ul>
{% endif %}
{% endif %}

<p><a href="#" onClick="javascript:window.close();">Close</a></p>

{% endblock %}

invoicer/templates/invoicer/startinvoice.html
{% extends "base.html" %}
{% load static %}
{% block scripts %}
<script type="text/javascript" src="{% static "select2.min.js" %}"></script>
<link rel="STYLESHEET" type="text/css" href="{% static "select2.min.css" %}">
{% endblock %}
{% block title %}Choose contact for invoice{% endblock %}
{% block body %}
<h1>Milton Beer Invoice Tool</h1>

<div class="accordion-wrapper">
<div id="accordion">
  <h3>Contacts</h3>
  <div>
    <h4>Create an invoice or bill</h4>
    <form id="contactform" method="POST">{% csrf_token %}
      <p><label for="id_contact">Contact name:</label>
	<select name="contact" id="id_contact">
	</select>
	<p></p>
	<button type="submit" name="invoice">Create invoice to customer</button>
	<button type="submit" name="bill">Enter bill from supplier</button>
    </form>
    <hr>
    <p><a href="https://go.xero.com/organisationlogin/default.aspx?shortcode={{shortcode}}&redirecturl=/Contacts/Edit.aspx">Add a new
	contact.  (Contacts cannot be removed once added.)</a></p>
    <p><a href="https://go.xero.com/organisationlogin/default.aspx?shortcode={{shortcode}}&amp;redirecturl=/AccountsReceivable/Search.aspx?invoiceStatus=INVOICESTATUS/DRAFT">Go to draft invoices</a></p>
  </div>
  <h3>Maintenance options</h3>
  <div>
    <p><a href="{% url "add-product" %}" target="_blank">Add a product</a></p>
    <p><a href="{% url "admin:invoicer_product_changelist" %}">Edit or remove products</a></p>

    {% if bands %}
    <p>View or update a price band:</p>
    <ul>
      {% for b in bands %}
      <li><a href="{% url "priceband" b.pk %}">{{b.name}}</a></li>
      {% endfor %}
    </ul>
    {% endif %}

    <p><a href="{% url "admin:invoicer_priceband_changelist" %}">Add
	or remove price bands</a></p>

    <p><a href="{% url "admin:invoicer_price_changelist" %}">Add, edit or remove price rules</a></p>

    <p><a href="{% url "admin:index" %}">Other maintenance options</a></p>
    <form method="POST">{% csrf_token %}
	<button type="submit" name="xero-disconnect">Disconnect from Xero</button>
    </form>
  </div>
</div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $( "#accordion" ).accordion();
    $('#id_contact').select2({
      width: '300px',
      ajax: {
        url: '{% url "contact-completions" %}',
        dataType: 'json',
        delay: 250
      },
      minimumInputLength: 2,
      placeholder: 'Choose a contact'
    });
    // hack to fix jquery 3.6 focus security patch that bugs auto
    // focus in select2
    $(document).on('select2:open', () => {
      document.querySelector('.select2-search__field').focus();
    });
  });
</script>

{% endblock %}

invoicer/templates/invoicer/xeroerror.html
{% extends "base.html" %}
{% load static %}
{% block title %}Connection error{% endblock %}
{% block body %}
<h1>Error connecting to Xero</h1>

<p>The connection to Xero did not succeed.</p>

<p>The error returned by Xero was: {{error}}</p>

<p><a href="{% url "new-invoice" %}">Click here to try again</a></p>

{% endblock %}